# Generated by Django 5.2.5 on 2026-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("department", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
