# Generated by Django 5.2.5 on 2026-03-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_leave_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="payroll",
            old_name="salary",
            new_name="basic_salary",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-08-29 00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payroll",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-08-29 00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payroll",
            name="month",
            field=models.CharField(default="2025-08-29 00:00", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                ],
                default="present",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("employee", "month")},
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.department"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
                    ),
                ),
            ],
        ),
    ]
