# Generated by Django 6.0.3 on 2026-03-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.CharField(max_length=100),
        ),
    ]
