# Generated by Django 5.2.5 on 2026-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_alter_leave_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_profiles/"
            ),
        ),
    ]
