# Generated by Django 5.2.5 on 2026-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_employee_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="contract_copy",
            field=models.FileField(
                blank=True, null=True, upload_to="employee_contracts/"
            ),
        ),
    ]
