# Generated by Django 6.0.3 on 2026-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
