# Generated by Django 6.0.3 on 2026-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_job_application_link_job_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Closing Soon', 'Closing Soon')], default='Open', max_length=20),
        ),
    ]
