# Generated by Django 6.0.1 on 2026-03-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('current_stage', models.CharField(choices=[('Applied', 'Applied'), ('Phone Screen', 'Phone Screen'), ('Technical Interview', 'Technical Interview'), ('HR Interview', 'HR Interview'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.job')),
            ],
        ),
    ]
