# Generated by Django 6.0.1 on 2026-03-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='onboarding_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_stage',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
