# Generated by Django 6.0.3 on 2026-03-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_interviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('employee_of_the_month', 'Employee of the month'), ('certification', 'Certification'), ('service_awards', 'Service Award')], max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'achievement_type', 'description')},
            },
        ),
    ]
